apiVersion: v1
kind: PersistentVolume
metadata:
  name: euro-champ-v2-pv-2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: euro2-web-disk
    fsType: ext4
