apiVersion: v1
kind: Service
metadata:
  name: euro-champ-web
  labels:
    app: euro-champ-v2
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  # loadBalancerIP: 35.187.115.68
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: euro-champ-v2
    tier: frontend
